### ISSUE TITLE
Npm run build fails on Windows

### ISSUE THREAD

**Issue by richie50** [fullcalendar/scheduler-typescript-example#1]
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullcalendar-scheduler-typescript-example@1.0.0 build: `./node_modules/webpack/bin/webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fullcalendar-scheduler-typescript-example@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by acerix** [comment]
Thanks for the report, should be working now.

**Comment by richie50** [comment]
:)
